=== xTheodor/BI-XML/validation/country.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT country (introduction,section+)>
<!ATTLIST country
  id CDATA #REQUIRED
  from CDATA #REQUIRED>

<!ELEMENT introduction (name,background)>

<!ELEMENT section (detail|nested-detail|list-detail|histogram)+>
<!ATTLIST section
  name CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT background (paragraph)+>

<!ELEMENT paragraph (#PCDATA)>

<!ELEMENT detail (#PCDATA)>
<!ATTLIST detail
  name CDATA #REQUIRED>

<!ELEMENT nested-detail (detail|list-detail)+>
<!ATTLIST nested-detail
  name CDATA #REQUIRED>

<!ELEMENT list-detail (list-item)+>
<!ATTLIST list-detail
  name CDATA #REQUIRED>

<!ELEMENT list-item (#PCDATA)>

<!ELEMENT histogram (entry)+>
<!ATTLIST histogram
  name CDATA #REQUIRED
  unit CDATA #IMPLIED>

<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry
  from_age CDATA #IMPLIED
  to_age CDATA #IMPLIED>

=== xTheodor/BI-XML/data/czechia.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE country SYSTEM "../validation/country.dtd">
<country from="https://www.cia.gov/library/publications/the-world-factbook/geos/ez.html" id="czechia">
    <introduction>
        <name>Czechia</name>
        <background>
            <paragraph>At the close of World War I, the Czechs and Slovaks of the former Austro-Hungarian Empire merged to form Czechoslovakia. During the interwar years, having rejected a federal system, the new country's predominantly Czech leaders were frequently preoccupied with meeting the increasingly strident demands of other ethnic minorities within the republic, most notably the Slovaks, the Sudeten Germans, and the Ruthenians (Ukrainians). On the eve of World War II, Nazi Germany occupied the territory that today comprises Czechia, and Slovakia became an independent state allied with Germany. After the war, a reunited but truncated Czechoslovakia (less Ruthenia) fell within the Soviet sphere of influence. In 1968, an invasion by Warsaw Pact troops ended the efforts of the country's leaders to liberalize communist rule and create "socialism with a human face," ushering in a period of repression known as "normalization." The peaceful "Velvet Revolution" swept the Communist Party from power at the end of 1989 and inaugurated a return to democratic rule and a market economy. On 1 January 1993, the country underwent a nonviolent "velvet divorce" into its two national components, the Czech Republic and Slovakia. The Czech Republic joined NATO in 1999 and the European Union in 2004. The country added the short-form name Czechia in 2016, while continuing to use the full form name, Czech Republic.</paragraph>
        </background>
    </introduction>
    <section name="Geography">
        <detail name="Location">Central Europe, between Germany, Poland, Slovakia, and Austria</detail>
        <detail name="Coordinates">49 45 N, 15 30 E</detail>
        <detail name="Coastline">0 km (landlocked)</detail>
        <detail name="Climate">temperate; cool summers; cold, cloudy, humid winters</detail>
        <detail name="Terrain">Bohemia in the west consists of rolling plains, hills, and plateaus surrounded by low mountains; Moravia in the east consists of very hilly country</detail>
        <list-detail name="Natural resources">
            <list-item>hard coal</list-item>
            <list-item>soft coal</list-item>
            <list-item>kaolin</list-item>
            <list-item>clay</list-item>
            <list-item>graphite</list-item>
            <list-item>timber</list-item>
            <list-item>arable land</list-item>
        </list-detail>
        <detail name="Irrigated land">320 sq km (2012)</detail>
        <list-detail name="Natural hazards">
            <list-item>flooding</list-item>
        </list-detail>
        <list-detail name="Current environment issues">
            <list-item>air and water pollution in areas of northwest Bohemia and in northern Moravia around Ostrava present health risks</list-item>
            <list-item>acid rain damaging forests</list-item>
            <list-item>land pollution caused by industry, mining, and agriculture</list-item>
        </list-detail>
        <detail name="Population - distribution">a fairly even distribution throughout most of the country, but the northern and eastern regions tend to have larger urban concentrations</detail>
        <nested-detail name="Area">
            <detail name="total">78,867 sq km</detail>
            <detail name="land">77,247 sq km</detail>
            <detail name="water">1,620 sq km</detail>
        </nested-detail>
        <detail name="Maritime claims">none (landlocked)</detail>
        <nested-detail name="Land use">
            <detail name="agricultural land">54.8% (2011 est.)</detail>
            <detail name="arable land">41% (2011 est.) / permanent crops: 1% (2011 est.) / permanent pasture: 12.8% (2011 est.)</detail>
            <detail name="forest">34.4% (2011 est.)</detail>
            <detail name="other">10.8% (2011 est.)</detail>
        </nested-detail>
        <nested-detail name="Environment international agreements">
            <list-detail name="party to">
                <list-item>Air Pollution</list-item>
                <list-item>Air Pollution-Nitrogen Oxides</list-item>
                <list-item>Air Pollution-Persistent Organic Pollutants</list-item>
                <list-item>Air Pollution-Sulfur 85</list-item>
                <list-item>Air Pollution-Sulfur 94</list-item>
                <list-item>Air Pollution-Volatile Organic Compounds</list-item>
                <list-item>Antarctic-Environmental Protocol</list-item>
                <list-item>Antarctic Treaty</list-item>
                <list-item>Biodiversity</list-item>
                <list-item>Climate Change</list-item>
                <list-item>Climate Change-Kyoto Protocol</list-item>
                <list-item>Desertification</list-item>
                <list-item>Endangered Species</list-item>
                <list-item>Environmental Modification</list-item>
                <list-item>Hazardous Wastes</list-item>
                <list-item>Law of the Sea</list-item>
                <list-item>Ozone Layer Protection</list-item>
                <list-item>Ship Pollution</list-item>
                <list-item>Wetlands</list-item>
                <list-item>Whaling</list-item>
            </list-detail>
            <detail name="signed, but not ratified">none of the selected agreements</detail>
        </nested-detail>
        <nested-detail name="Elevation">
            <detail name="mean-elevation">433 m</detail>
            <detail name="lowest point">Labe (Elbe) River 115 m</detail>
            <detail name="highest point">Snezka 1,602 m</detail>
        </nested-detail>
    </section>
    <section name="People and society">
        <detail name="Population">10,702,498 (July 2020 est.)</detail>
        <list-detail name="Ethnic groups">
            <list-item>Czech 64.3%</list-item>
            <list-item>Moravian 5%</list-item>
            <list-item>Slovak 1.4%</list-item>
            <list-item>other 1.8%</list-item>
            <list-item>unspecified 27.5% (2011 est.)</list-item>
        </list-detail>
        <list-detail name="Languages">
            <list-item>Czech (official) 95.4%</list-item>
            <list-item>Slovak 1.6%</list-item>
            <list-item>other 3% (2011 census)</list-item>
        </list-detail>
        <list-detail name="Religions">
            <list-item>Roman Catholic 10.4%</list-item>
            <list-item>Protestant (includes Czech Brethren and Hussite) 1.1%</list-item>
            <list-item>other and unspecified 54%</list-item>
            <list-item>none 34.5% (2011 est.)</list-item>
        </list-detail>
        <detail name="Population growth rate">0.06% (2020 est.)</detail>
        <detail name="Birth rate">8.9 births/1,000 population (2020 est.)</detail>
        <detail name="Death rate">10.7 deaths/1,000 population (2020 est.)</detail>
        <detail name="Net migration rate">2.3 migrant(s)/1,000 population (2020 est.)</detail>
        <detail name="Population distribution">a fairly even distribution throughout most of the country, but the northern and eastern regions tend to have larger urban concentrations</detail>
        <detail name="Mother's mean age at first birth">28.1 years (2014 est.)</detail>
        <detail name="Maternal mortality rate">3 deaths/100,000 live births (2017 est.)</detail>
        <detail name="Total fertility rate">1.48 children born/woman (2020 est.)</detail>
        <detail name="Health expenditures">7.2% (2017)</detail>
        <detail name="Physicians density">4.07 physicians/1,000 population (2017)</detail>
        <detail name="Hospital bed density">6.6 beds/1,000 population (2017)</detail>
        <list-detail name="Urban areas">
            <list-item>1.306 million PRAGUE (capital) (2020)</list-item>
        </list-detail>
        <detail name="HIV/AIDS - adult prevalence rate">0.1% (2018 est.)</detail>
        <detail name="HIV/AIDS - people living with HIV/AIDS">4,400 (2018 est.)</detail>
        <detail name="HIV/AIDS - deaths">100 (2018 est.)</detail>
        <detail name="Obesity - adult prevalence rate">26% (2016)</detail>
        <detail name="Education expenditures">5.6% of GDP (2016)</detail>
        <nested-detail name="Nationality">
            <detail name="noun">Czech(s)</detail>
            <detail name="adjective">Czech</detail>
        </nested-detail>
        <nested-detail name="Dependency ratios">
            <detail name="total dependency ratio">56</detail>
            <detail name="youth dependency ratio">24.6</detail>
            <detail name="elderly dependency ratio">31.4</detail>
        </nested-detail>
        <nested-detail name="Median age">
            <detail name="total">43.3 years</detail>
            <detail name="male">42 years</detail>
            <detail name="female">44.7 years (2020 est.)</detail>
        </nested-detail>
        <nested-detail name="Urbanization">
            <detail name="urban population">74.1% of total population (2020)</detail>
            <detail name="rate of urbanization">0.21% annual rate of change (2015-20 est.)</detail>
        </nested-detail>
        <nested-detail name="Infant mortality rate">
            <detail name="total">2.6 deaths/1,000 live births</detail>
            <detail name="male">2.8 deaths/1,000 live births</detail>
            <detail name="female">2.5 deaths/1,000 live births (2020 est.)</detail>
        </nested-detail>
        <nested-detail name="Life expectancy at birth">
            <detail name="total">79.3 years</detail>
            <detail name="male">76.3 years</detail>
            <detail name="female">82.4 years (2020 est.)</detail>
        </nested-detail>
        <nested-detail name="School life expectancy (primary to tertiary education)">
